//MAIN SETTINGS BASIX

//Addon Whitelist
_Setting22 = true; //Scan player PBO files against server PBO files and detect discrepancies ("true" is on, "false" is off, set to true by default)
_Setting23 = ["3den_Objects.pbo",
"AC1D_base.pbo",
"AC1D_ford_mustang_NFS_SPEC.pbo",
"ace_advanced_ballistics.pbo",
"ace_advanced_fatigue.pbo",
"ace_advanced_throwing.pbo",
"ace_ai.pbo",
"ace_aircraft.pbo",
"ace_apl.pbo",
"ace_arsenal.pbo",
"ace_atragmx.pbo",
"ace_attach.pbo",
"ace_backpacks.pbo",
"ace_ballistics.pbo",
"ace_captives.pbo",
"ace_cargo.pbo",
"ace_chemlights.pbo",
"ace_common.pbo",
"ace_concertina_wire.pbo",
"ace_cookoff.pbo",
"ace_dagr.pbo",
"ace_disarming.pbo",
"ace_disposable.pbo",
"ace_dogtags.pbo",
"ace_dragging.pbo",
"ace_explosives.pbo",
"ace_fastroping.pbo",
"ace_fcs.pbo",
"ace_finger.pbo",
"ace_flashlights.pbo",
"ace_flashsuppressors.pbo",
"ace_fonts.pbo",
"ace_frag.pbo",
"ace_gestures.pbo",
"ace_gforces.pbo",
"ace_goggles.pbo",
"ace_grenades.pbo",
"ace_gunbag.pbo",
"ace_hearing.pbo",
"ace_hellfire.pbo",
"ace_hitreactions.pbo",
"ace_huntir.pbo",
"ace_interact_menu.pbo",
"ace_interaction.pbo",
"ace_inventory.pbo",
"ace_javelin.pbo",
"ace_kestrel4500.pbo",
"ace_laser.pbo",
"ace_laserpointer.pbo",
"ace_logistics_uavbattery.pbo",
"ace_logistics_wirecutter.pbo",
"ace_magazinerepack.pbo",
"ace_main.pbo",
"ace_map.pbo",
"ace_map_gestures.pbo",
"ace_maptools.pbo",
"ace_markers.pbo",
"ace_maverick.pbo",
"ace_medical.pbo",
"ace_medical_ai.pbo",
"ace_medical_blood.pbo",
"ace_medical_menu.pbo",
"ace_microdagr.pbo",
"ace_minedetector.pbo",
"ace_missileguidance.pbo",
"ace_missionmodules.pbo",
"ace_mk6mortar.pbo",
"ace_modules.pbo",
"ace_movement.pbo",
"ace_mx2a.pbo",
"ace_nametags.pbo",
"ace_nightvision.pbo",
"ace_nlaw.pbo",
"ace_noidle.pbo",
"ace_noradio.pbo",
"ace_norearm.pbo",
"ace_optics.pbo",
"ace_optionsmenu.pbo",
"ace_overheating.pbo",
"ace_overpressure.pbo",
"ace_parachute.pbo",
"ace_pylons.pbo",
"ace_quickmount.pbo",
"ace_rangecard.pbo",
"ace_realisticnames.pbo",
"ace_realisticweights.pbo",
"ace_rearm.pbo",
"ace_recoil.pbo",
"ace_refuel.pbo",
"ace_reload.pbo",
"ace_reloadlaunchers.pbo",
"ace_repair.pbo",
"ace_respawn.pbo",
"ace_safemode.pbo",
"ace_sandbag.pbo",
"ace_scopes.pbo",
"ace_slideshow.pbo",
"ace_smallarms.pbo",
"ace_spectator.pbo",
"ace_spottingscope.pbo",
"ace_switchunits.pbo",
"ace_tacticalladder.pbo",
"ace_tagging.pbo",
"ace_thermals.pbo",
"ace_trenches.pbo",
"ace_tripod.pbo",
"ace_ui.pbo",
"ace_vector.pbo",
"ace_vehiclelock.pbo",
"ace_vehicles.pbo",
"ace_viewdistance.pbo",
"ace_weaponselect.pbo",
"ace_weather.pbo",
"ace_winddeflection.pbo",
"ace_yardage450.pbo",
"ace_zeus.pbo",
"Acessorios.pbo",
"acex_fortify.pbo",
"acex_headless.pbo",
"acex_killtracker.pbo",
"acex_main.pbo",
"acex_sitting.pbo",
"acex_viewrestriction.pbo",
"acex_volume.pbo",
"adv_aceCPR.pbo",
"AR_AdvancedRappelling.pbo",
"ARC_Heads.pbo",
"asdg_jointrails.pbo",
"babe_core.pbo",
"babe_em.pbo",
"babe_int.pbo",
"bandeiras.pbo",
"bg_weaponframework.pbo",
"BloodSplatter.pbo",
"bma3_bushmaster.pbo",
"bma3_bushmaster_anim.pbo",
"bma3_bushmaster_config.pbo",
"bma3_bushmaster_data.pbo",
"bma3_bushmaster_sounds.pbo",
"bope_acu.pbo",
"bope_boonies.pbo",
"bope_insignia.pbo",
"bope_vests2.pbo",
"bopemod.pbo",
"CAG_416.pbo",
"cba_accessory.pbo",
"cba_ai.pbo",
"cba_arrays.pbo",
"cba_common.pbo",
"cba_diagnostic.pbo",
"cba_events.pbo",
"cba_hashes.pbo",
"cba_help.pbo",
"cba_jr.pbo",
"cba_jr_prep.pbo",
"cba_keybinding.pbo",
"cba_main.pbo",
"cba_main_a3.pbo",
"cba_modules.pbo",
"cba_music.pbo",
"cba_network.pbo",
"cba_settings.pbo",
"cba_statemachine.pbo",
"cba_strings.pbo",
"cba_ui.pbo",
"cba_ui_helper.pbo",
"cba_vectors.pbo",
"cba_versioning.pbo",
"cba_xeh.pbo",
"Charlieco89_206.pbo",
"Charlieco89_206_civ.pbo",
"Charlieco89_c4h_civ.pbo",
"Charlieco89_Dacia_Duster.pbo",
"Charlieco89_FocusRS_civ.pbo",
"Charlieco89_Transit.pbo",
"CSW_FN57.pbo",
"CUP_BaseConfigs.pbo",
"CUP_BaseData.pbo",
"CUP_Weapons_AA12.pbo",
"CUP_Weapons_AK.pbo",
"CUP_Weapons_AmmoBoxes.pbo",
"CUP_Weapons_Ammunition.pbo",
"CUP_Weapons_AS50.pbo",
"CUP_Weapons_AWM.pbo",
"CUP_Weapons_Backpacks.pbo",
"CUP_Weapons_Bizon.pbo",
"CUP_Weapons_Colt1911.pbo",
"CUP_Weapons_Compact.pbo",
"CUP_Weapons_Compatibility.pbo",
"CUP_Weapons_Curator.pbo",
"CUP_Weapons_CZ750.pbo",
"CUP_Weapons_CZ805.pbo",
"CUP_Weapons_Duty.pbo",
"CUP_Weapons_DynamicLoadout.pbo",
"CUP_Weapons_East_Attachments.pbo",
"CUP_Weapons_Evo.pbo",
"CUP_Weapons_FNFAL.pbo",
"CUP_Weapons_G36.pbo",
"CUP_Weapons_Glock17.pbo",
"CUP_Weapons_GrenadeLaunchers.pbo",
"CUP_Weapons_Grenades.pbo",
"CUP_Weapons_Huntingrifle.pbo",
"CUP_Weapons_Igla.pbo",
"CUP_Weapons_Items.pbo",
"CUP_Weapons_KSVK.pbo",
"CUP_Weapons_L110.pbo",
"CUP_Weapons_L129.pbo",
"CUP_Weapons_LeeEnfield.pbo",
"CUP_Weapons_M1014.pbo",
"CUP_Weapons_M107.pbo",
"CUP_Weapons_M110.pbo",
"CUP_Weapons_M136.pbo",
"CUP_Weapons_M14.pbo",
"CUP_Weapons_M14_DMR.pbo",
"CUP_Weapons_M16.pbo",
"CUP_Weapons_M24.pbo",
"CUP_Weapons_M240.pbo",
"CUP_Weapons_M249.pbo",
"CUP_Weapons_M47.pbo",
"CUP_Weapons_M60E4.pbo",
"CUP_Weapons_M72A6.pbo",
"CUP_Weapons_M9.pbo",
"CUP_Weapons_MAAWS.pbo",
"CUP_Weapons_Makarov.pbo",
"CUP_Weapons_Metis_AT_13.pbo",
"CUP_Weapons_MicroUZI.pbo",
"CUP_Weapons_Mk48.pbo",
"CUP_Weapons_MP5.pbo",
"CUP_Weapons_NLAW.pbo",
"CUP_Weapons_NVG.pbo",
"CUP_Weapons_PB_6P9.pbo",
"CUP_Weapons_Phantom.pbo",
"CUP_Weapons_PK.pbo",
"CUP_Weapons_Pods.pbo",
"CUP_Weapons_Put.pbo",
"CUP_Weapons_Revolver.pbo",
"CUP_Weapons_RPG18.pbo",
"CUP_Weapons_RPG7.pbo",
"CUP_Weapons_SA58.pbo",
"CUP_Weapons_SA61.pbo",
"CUP_Weapons_Saiga12K.pbo",
"CUP_Weapons_Shield.pbo",
"CUP_Weapons_SMAW.pbo",
"CUP_Weapons_Sounds.pbo",
"CUP_Weapons_SoundShaders.pbo",
"CUP_Weapons_Stinger.pbo",
"CUP_Weapons_Strela_2.pbo",
"CUP_Weapons_SVD.pbo",
"CUP_Weapons_UK59.pbo",
"CUP_Weapons_VehicleWeapons.pbo",
"CUP_Weapons_VSS.pbo",
"CUP_Weapons_WeaponsCore.pbo",
"CUP_Weapons_WeaponsData.pbo",
"CUP_Weapons_West_Attachments.pbo",
"CUP_Weapons_XM8.pbo",
"data.pbo",
"dbo_old_bike.pbo",
"dbo_wheelchair.pbo",
"eas_civil3.pbo",
"EB_IA2.pbo",
"FaisalAlYahya_Carpack.pbo",
"FaisalAlYahya_CrownVicPolice.pbo",
"FaisalAlYahya_Yokun2015Police.pbo",
"fhq_accessories.pbo",
"fhq_m4_a3.pbo",
"gign.pbo",
"hlc_core.pbo",
"hlc_wp_ak.pbo",
"hlc_wp_aug.pbo",
"hlc_WP_FAL.pbo",
"hlc_wp_mp5.pbo",
"hlc_wp_sigamt.pbo",
"HueyPack.pbo",
"jbad_misc.pbo",
"Jbad_Sounds.pbo",
"Jbad_Structures.pbo",
"jsrs_soundmod_cfg_apcs.pbo",
"jsrs_soundmod_cfg_bullethits.pbo",
"jsrs_soundmod_cfg_cars.pbo",
"jsrs_soundmod_cfg_environment.pbo",
"jsrs_soundmod_cfg_explosions.pbo",
"jsrs_soundmod_cfg_fake1.pbo",
"jsrs_soundmod_cfg_framework.pbo",
"jsrs_soundmod_cfg_helicopters.pbo",
"jsrs_soundmod_cfg_jets.pbo",
"jsrs_soundmod_cfg_movement.pbo",
"jsrs_soundmod_cfg_soniccracks.pbo",
"jsrs_soundmod_cfg_tanks.pbo",
"jsrs_soundmod_cfg_trucks.pbo",
"jsrs_soundmod_cfg_uavs.pbo",
"jsrs_soundmod_cfg_vtols.pbo",
"jsrs_soundmod_cfg_weapons.pbo",
"jsrs_soundmod_snd_apcs.pbo",
"jsrs_soundmod_snd_bullethits.pbo",
"jsrs_soundmod_snd_cars.pbo",
"jsrs_soundmod_snd_environment.pbo",
"jsrs_soundmod_snd_explosions.pbo",
"jsrs_soundmod_snd_helicopters.pbo",
"jsrs_soundmod_snd_jets.pbo",
"jsrs_soundmod_snd_movement.pbo",
"jsrs_soundmod_snd_soniccracks.pbo",
"jsrs_soundmod_snd_tanks.pbo",
"jsrs_soundmod_snd_trucks.pbo",
"jsrs_soundmod_snd_uavs.pbo",
"jsrs_soundmod_snd_vtols.pbo",
"jsrs_soundmod_snd_weapons.pbo",
"KA_weapon_functions.pbo",
"Kio_Balaclava.pbo",
"mea_military.pbo",
"min_rf_units.pbo",
"mm_bank.pbo",
"mm_buildings.pbo",
"mm_buildings2.pbo",
"mm_buildings3.pbo",
"mm_buildings4.pbo",
"MM_objects.pbo",
"mm_post.pbo",
"mm_residential.pbo",
"mm_residential2.pbo",
"MM_Shopping.pbo",
"mm_showroom.pbo",
"plp_containers.pbo",
"rainque_LeeEnfield.pbo",
"rkb_reichsflugscheibe.pbo",
"ryanzombies.pbo",
"UMI_Bomb_Vest.pbo",
"UMI_Electronics.pbo",
"UMI_Inventory.pbo",
"UMI_Mod.pbo",
"UMI_Static.pbo",
"UMI_Wearable.pbo",
"walker_a3_vehicles.pbo",
"xCam_EU.pbo",
"task_force_radio.pbo",
"task_force_radio_items.pbo"]; //Additional PBO files to add to the whitelist (e.g. ["CBA_A3.pbo","CBA_CORE.pbo"])

//Classname Whitelist
_Setting24 = false; //Scan player classnames against server classnames and detect discrepancies ("true" is on, "false" is off, set to true by default)
_Setting25 = [""]; //Additional classnames to add to the whitelist (e.g. ["LandVehicle_Duck","Gun_Cowboy"])

//Addon Blacklist                   HACKS
_Setting1 = true; //Scan player PBO files ("true" is on, "false" is off, set to false by default)
_Setting2 = ["devcon.pbo","DevCon.pbo","DEV_PostA3.pbo","DEV_CO_Dummy.pbo","NSS Admin Console.pbo","mpg_a3.pbo","NSS_AC_2.pbo"]; //Addons you don't wan't on your server (e.g. "devcon.pbo")

//Variable Blacklist
_Setting3 = true; //Detect player using Banned variable names ("true" is on, "false" is off, set to true by default)
_Setting4 = ["mainnext1","visualeffects1","iBeFlying","nonapsi_ef","ChangingBullets_xx",
"change_terrain_Metallica","HaxSmokeOn","DEV_CurrentDisplayIdd","DEV_ConsoleActive","DEV_DebugConsoleInputFields",
"DEV_UnitMapMarkersShown","DEV_UnitMapMarkerID","DEV_RemoteCodeLogic","scroll_m_init_star","xtags_star_xx",
"Monky_hax_dbclick","infammoON","raiinswalker","E_X_T_A_S_Y_ANTI_ANTI_HAX","E_X_T_A_S_Y_Init_Menu","E_X_T_A_S_Y_Wasteland_VF",
"E_X_T_A_S_Y_SpeedyGonzales","E_X_T_A_S_Y_AdminMenu_404","LYSTIC_MENU_LOADED","init_Fncvwr_menu_star","Monky_funcs_inited",
"airborne_spawn_vehicle_infiSTAR","Metallica_infiSTAR_hax_toggled","LysticsCode","color_list_lystic","LOLTOGGLESHITNIT"]; //Banned variable names (e.g. an array called: HaxSmokeOn)

//Classname Blacklist
_Setting16 = false; //Detect player using Banned classnames ("true" is on, "false" is off, set to false by default)
_Setting17 = ["DevCon","DEV_Background","DEV_Abort","GlobalExecuteButton_06","DEV_MiniMap","DevCon_Fired","DEV_MapReplacement"]; //Banned classnames list

//Server Speed Limit
_Setting5 = false; //Detect player speed hacking ("true" is on, "false" is off, set to false by default)
_Setting6 = 600; //Non-unit vehicle max speed on your server (Variable for detecting speed-hacking, set to 600 by default)

//Weapon Blacklist
_Setting7 = false; //Detect player using Banned weapon ("true" is on, "false" is off, set to false by default)
_Setting8 = ["srifle_GM6_F","srifle_GM6_camo_F","srifle_LRR_F","srifle_LRR_camo_F","launch_B_Titan_short_F","launch_B_Titan_F"]; //Weapons you can't obtain legitimately in your mission

//Vehicle Blacklist
_Setting9 = false; //Detect player using Banned vehicle ("true" is on, "false" is off, set to false by default)
_Setting10 = [""]; //Vehicles you can't obtain legitimately in your mission

//Anti-Teleport
_Setting11 = true; //Detect player teleport ("true" is on, "false" is off, set to true by default)

//Player Exemptions
_Setting12 = false; //Allow declared players to be exempt from Anti-Hack ("true" is on, "false" is off, set to false by default)
_Setting13 = [""]; //List of player UID's exempt from Anti-Hack

//Admin Menu
_Setting14 = false; //Enable BASIX admin menu system ("true" is on, "false" is off, set to false by default)
_Setting15 = [["76561198134612622","SuperAdmin"],["76561198090180406","SuperAdmin"]]; //List of admin UID's and level, structure [UID,LEVEL] e.g. [["123456","SuperAdmin"],["789123","Admin"],["456789","Moderator"]] (options: "SuperAdmin", "Admin", "Moderator")

//Permanent BASIX Bans
_Setting18 = true; //Enable BASIX permanent ban system, be warned possible security risk if enabled ("true" is on, "false" is off, set to true by default)

//BASIX Mission Disable
_Setting19 = false; //Disable BASIX for certain missions defined by ".pbo" name e.g. "SuperBattle_V1.pbo" ("true" is on, "false" is off, set to false by default)
_Setting20 = [""]; //Disabled mission PBO files

//CheatEngine Injector Scans
_Setting21 = true; //Allow BASIX to scan for indications of someone Injecting using CheatEngine ("true" is on, "false" is off, set to true by default)

//Chat-Loging
_Setting26 = true; //Allow BASIX to store chat conversations ("true" is on, "false" is off, set to true by default)
_Setting27 = true; //Enable word and phrase filter ("true" is on, "false" is off, set to false by default)
_Setting28 = ["porra","PORRA","caralho","CARALHO","FDP","fdp"]; //Filter list, capitals don't matter (e.g. ["fuck","cunt","I will kill your dog"])

//Chat-Commands
_Setting29 = true; //Enable chat based commands, found in "fn_BASIX_COMMANDS.sqf" ("true" is on, "false" is off, set to true by default)

//Version Checker
_Setting30 = true; //Enable version checker ("true" is on, "false" is off, set to true by default)





//End Of Settings ** Do Not Edit Below This Point **
BASIX_SETTINGS = compileFinal (format ['_return = [%1,%2,%3,%4,%5,%6,%7,%8,%9,%10,%11,%12,%13,%14,%15,%16,%17,%18,%19,%20,%21,%22,%23,%24,%25,%26,%27,%28,%29,%30]; _return',_Setting1,_Setting2,_Setting3,_Setting4,_Setting5,_Setting6,_Setting7,_Setting8,_Setting9,_Setting10,_Setting11,_Setting12,_Setting13,_Setting14,_Setting15,_Setting16,_Setting17,_Setting18,_Setting19,_Setting20,_Setting21,_Setting22,_Setting23,_Setting24,_Setting25,_Setting26,_Setting27,_Setting28,_Setting29,_Setting30]);
publicVariable "BASIX_SETTINGS";